### ISSUE TITLE
Strange behaviour of should_receive(:message).exactly(n).times

### ISSUE THREAD

**Issue by alanjsph** [rspec/rspec-dev#200]
car.rb

```ruby
class Car
  def initialize
    @brand          = 'unknown'
    @current_speed  = 0
    @max_speed      = 0
  end

  def drive
    p "Car started acclerating..."
    accelerate while @current_speed <= @max_speed
    p "Car reached maximum speed !"
  end

  def accelerate
    @current_speed += 1
    sleep 1
    print "-"
  end
end
```

car_spec.rb

```ruby
require 'spec_helper'
require_relative '../car'

RSpec.describe Car do
  let(:car) { Car.new }

  describe '#initialize' do
     it 'should have default properties initialized' do
      expect(car.instance_variable_get(:@brand)).to eq 'unknown'
      expect(car.instance_variable_get(:@current_speed)).to eq 0
      expect(car.instance_variable_get(:@max_speed)).to eq 0
    end
  end

  describe '#drive' do
    it 'should call #acclerate as long as current_speed is less than max_speed' do
      car.should_receive(:accelerate).exactly(9).times
      car.drive
    end
  end
end
```

expected behaviour

Should fail with message 
```
       (#<Car:0x00007fe4cc15cf08 @brand="unknown", @current_speed=0, @max_speed=0>).accelerate(no args)
           expected: 9 times with any arguments
           received: 1 times
```

actual behaviour 

```
Failures:

  1) Car#drive should call #acclerate as long as current_speed is less than max_speed
     Failure/Error: t.drive

       (#<Car:0x00007fc2f79604d0 @brand="unknown", @current_speed=0, @max_speed=1>).accelerate(no args)
           expected: 9 times with any arguments
           received: 10 times
     # ./car.rb:10:in `drive'
     # ./spec/car_spec.rb:19:in `block (3 levels) in <top (required)>'
```

Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.3)
    rake (12.3.0)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.1)

PLATFORMS
  ruby

DEPENDENCIES
  rake
  rspec

BUNDLED WITH
   1.16.1
```
